#!/bin/sh

user=$1

if [ -z "$user" ]
then
    echo 'usage: push [user]'
    exit 1
fi

if [ -z `pgrep mongod` ]
then
    echo 'make sure mongod is running before you push'
    exit 1
fi

echo "generating a static version of alexramsdell.com ... "
/usr/bin/env python ./freeze.py

if [ -e ./app/build/admin ]
then
    echo "deleting the admin section of the static build"
    rm -rf ./app/build/admin
fi

if test $?
then 
    echo "static site generated successfully."
    echo "copying static build to production ... " 
    rsync -avP --delete ./app/build/ alex@$box:/home/alex/alexramsdell.com/public_html/ --exclude=img 
else
    echo 'The frozen-flask build seems like it failed ... want to check and try again?' 
fi

echo "done!"
