#!/bin/bash
DB_LOCAL_EXPORT_DIR='/data/web/blog/db'
DB_REMOTE_EXPORT_DIR='/home/alexr'

mongoexport -d blog -c posts > $DB_LOCAL_EXPORT_DIR/posts.update &&\
rsync $DB_LOCAL_EXPORT_DIR/posts.update alexr@104.131.106.239:/home/alexr/

# remote commands
mongo blog --eval 'db.posts.drop()'
mongoimport -d blog -c posts < $DB_REMOTE_EXPORT_DIR/posts.update
