#!/bin/bash

function usage()
{
  echo "Usage: unpublish article1 [ .. article2]"
}


  [ "$#" -lt 1 ] && usage && exit 1 

  for f in "$@"
  do
    if (echo "$f" | grep -q __[0-9])
    then
      echo "ERROR: $f seems to have a time stamp already. Refusing to publish."
      continue
    elif ! $(echo "$f" | grep -q '.md')
    then
      echo "ERROR: $f does not look like a markdown file. Refusing to publish" 
      continue
    else
      echo "- Publishing $f ..."
      mv "$f" "$(echo $f | sed "s/\(.*\).md/\1__$(date '+%m%d%Y').md/g" )"
      echo "+ file $f has been published!"
    fi
  done
